### ISSUE TITLE
Add option to create configured kraken source tree (for u-root)

### ISSUE THREAD

**Issue by synackd** [hpc/kraken#100]
In order to be able to have kraken be a u-root command (for future firmware aspirations), it would be useful to add an option to `kraken-build` to generate a u-root-embeddable source tree.

**Comment by synackd** [comment]
See branch on my fork: [`u-kraken`](https://github.com/synackd/kraken/tree/u-kraken)

**Comment by synackd** [comment]
@jlowellwofford Would it be preferred to use one set of generated templates for both the u-root version of the source tree and the building of Kraken (similar to passing `-noclean`) or to leave the templates for building kraken untouched and regenerate the templates for the u-root version?

The former seems most efficient, but the second option will eliminate extraneous and conflicting files (such as the `main` binary) in the kraken source tree for u-root.

**Comment by synackd** [comment]
I am currently getting the following error when building kraken from the compiled templates in a different kraken source tree than kraken proper:
```go
# github.com/u-root/u-root/cmds/exp/kraken/src
./main.go:169:23: cannot use any (type *"github.com/u-root/u-root/cmds/exp/kraken/vendor/github.com/golang/protobuf/ptypes/any".Any) as type *"github.com/hpc/kraken/vendor/github.com/golang/protobuf/ptypes/any".Any in argument to restapi.UpdateConfig
2019/09/16 00:59:36 failed to build linux-amd64 for u-root: exit status 2
```
Perhaps I need to build kraken in the kraken proper source tree first and copy the binary over, then copy the source tree over? That doesn't seem useful if one wanted to rebuild kraken from the compiled templates in the kraken u-root command directory.

**Comment by jlowellwofford** [comment]
This is an error you will get if you try to build a non-go modules package outside of your proper GOPATH directory.  It's possible that the way u-root builds, this won't work right.  But, as a first try, make sure the source dir contains go.{mod,sum}.

**Comment by synackd** [comment]
I ended up solving this by writing a simple search-and-replace function for files to replace imports containing "github.com/hpc/kraken/*" with "github.com/u-root/u-root/cmds/exp/kraken/*". `go.mod` and `go.sum` are present as well.

**Comment by jlowellwofford** [comment]
Seems like there should be a cleaner way to do this... but maybe it will do for now.  Is it functional?  You can go ahead and submit a PR when you're ready.

**Comment by synackd** [comment]
It definitely builds. I ran it with qemu and got a shell, but didn't see the command in `PATH`. I didn't get time to fix this, but I'll examine it this week.

**Comment by synackd** [comment]
I've finally gotten a minimal kraken build into u-root that can run. Now, it's a matter of configuration and fine tuning to get the desired result.

**Comment by synackd** [comment]
I just realized that `lib/` is used by kraken itself and not kraken-build. Is there another place for my utility functions or are they confined to `kraken-build.go`?

**Comment by synackd** [comment]
Merged. Closing.
