### ISSUE TITLE
Address the way kraken calls services

### ISSUE THREAD

**Issue by synackd** [hpc/kraken#185]
Currently, the way that kraken launches services is that it calls kraken with an `argv[0]` of the format `[kraken:<service_ID>]`; however, since u-root uses a single BusyBox binary with symlinks for each command, it will not be able to "find" kraken when doing this since the binary uses `argv[0]` to determine what command was called.

We should consider modifying this mechanism to avoid hack solutions when generating u-root-compatible kraken source trees (e.g. modifying the service-launching code during generation).

**Comment by jlowellwofford** [comment]
Resolved by #220
