### ISSUE TITLE
Export mutation graph in json/dot syntax through restapi

### ISSUE THREAD

**Issue by jlowellwofford** [hpc/kraken#30]
Could be done by reworking DumpGraph and adding a hook in restapi.

This would allow easy inspection and debugging of the mutation graph.

**Comment by kpelzel0522** [comment]
Is there anyway to access the sme from the kraken apiServer? Would the best solution be to query the kraken API server to get info from the sme?

**Comment by jlowellwofford** [comment]
Good question.  Maybe we can extend the Query interface?  Currently it only interacts with the SDE, but it could be made to interact with the SME as well (there may be future features other than this that could benefit as well).

This is a bit more complicated that I was thinking at first though…

Take a look at the Run function in the SDE to see how that end of the Query engine works.  You’d need to setup a channel that the Query interface communicated with the SME through.  Haven’t yet verified all of this though.
—
Lowell

On Jan 24, 2019, at 10:38 AM, Kevin Pelzel <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there anyway to access the sme from the kraken apiServer? Would the best solution be to query the kraken API server to get info from the sme?

**Comment by kpelzel0522** [comment]
Correct me if I'm wrong, so currently the query engine is defined in kraken's context and is passed the channel that talks to the sde. Would we be running two query engines or would we rework the query engine to talk to multiple channels (both the sde and the sme)?

**Comment by jlowellwofford** [comment]
That’s right, currently it just talks to the SDE through a channel.  My thought is that we would make a similar channel for the SME.  Which channel gets used could be decided by which query method was called.
—
Lowell

On Jan 24, 2019, at 4:04 PM, Kevin Pelzel <notifications@github.com<mailto:notifications@github.com>> wrote:


Correct me if I'm wrong, so currently the query engine is defined in kraken's context and is passed the channel that talks to the sde. Would we be running two query engines or would we rework the query engine to talk to multiple channels (both the sde and the sme)?

**Comment by jlowellwofford** [comment]
This was added in #69
