### ISSUE TITLE
Nodes gets stuck in boot cycle if kraken dies

### ISSUE THREAD

**Issue by caskie** [hpc/kraken#65]
Booted the vbox example and `ssh`ed  into the node; killed kraken service and the node went into an infinite booting loop.  The loop was stopped by manually turning off node through the dashboard.

**Comment by kpelzel** [comment]
This is an old issue, but I have more info on this bug. 

**Setup:**
Booted raspberry pi cluster and waited for all nodes to be in sync state. Then manually killed all the nodes. Every node came back except for one (node: 0F93D098-B28D-F5A0-95D0-BA7FD81C9B7E). This node was stuck in a boot loop and displayed no current mutation in the state graph on the dashboard.

**Discoveries:**
After looking through the log, you can see the node progress through the mutation chain, but the chain keeps growing. It eventually grows to a chain containing over 60 mutations. 

Not sure if this is normal behavior, but I found it interesting.
[kraken.log](https://github.com/hpc/kraken/files/3785145/kraken.log)
