### ISSUE TITLE
Add CI Integration

### ISSUE THREAD

**Issue by bensallen** [hpc/kraken#78]
The project should have CI based checks integrated. I've had good luck with CircleCI, but I can certainly help with any other preferred tooling.

A reasonable example with CircleCI: https://github.com/cfg8er/cfg8er/blob/master/.circleci/config.yml.

#74 and #73 were the start of some initial work towards this.

TODOs:
- Existing tests passing (#75) 
- Golint (or equiv. like `revive`) passing. Primarily appears to be exported functions, const, etc without comments currently.
- Add CI Config
- Enable CI integration and enforce branch protection on the Github project

**Comment by jlowellwofford** [comment]
I added CodeFactor that does some linting yesterday.  I haven't used it before, but so far it seems to do the job pretty well.  The main barrier on the rest is #75, as you noted.

**Comment by bensallen** [comment]
CodeFactor looks useful. Appears to be smaller subset of what gometalinter will show for Go files, but is more general so includes shellcheck for bash, and yamllint for the yaml files.

Other options:

- GolangCI - https://golangci.com (hosted), or https://github.com/golangci/golangci-lint (run via CI/Editor/CLI). The hosted version looks nice as it does inline GitHub PR comments.

Appears the best way to run it via CLI on Kraken is: `golangci-lint run . core extensions/... modules/... utils/...`. Appears a regular `golangci-lint run ./...` breaks due to `go list  -compiled ./...`, isn't liking the modules and extension directories not having any go files directly under that directory.

- u-root's CircleCI config is running gometalinter with a number of excludes: https://github.com/u-root/u-root/blob/master/.circleci/config.yml. I'm not sure if `gometalinter --vendor` is working with go modules. I can't easily get it to ignore vendors.

- revive - https://revive.run, same checks as golint but faster. This is what I currently have my editor run on every file save. For CI golangci-lint or gometalinter should be able to replace golint/revive.

- https://goreportcard.com/report/github.com/hpc/kraken, this doesn't appear to have GitHub integration beyond a badge.

**Comment by jlowellwofford** [comment]
I opted to just setup CircleCI for now.  It runs a set of tests in `core/tests` (incomplete), builds `kraken-build`, and does the `vbox.yml` build.  It's a start.  I'm planning to look a little closer at GolangCI.

**Comment by jlowellwofford** [comment]
This will require ongoing work, but I'm going to go ahead and close the issue.
