### ISSUE TITLE
Consider Migration to Go Modules

### ISSUE THREAD

**Issue by bensallen** [hpc/kraken#79]
It would be useful to migrate to Go Modules, eg:

```
go mod init
go mod vendor
```

The primary benefit is no longer having to make use of GOPATH.

**Comment by jlowellwofford** [comment]
I'm going to play around with this.  Independence of GOPATH would definitely be nice.

**Comment by jlowellwofford** [comment]
I got a branch working with this ("feature/gomod" on my fork).  I had to modify a few things to make it able to live outside of GOPATH, but I think I've got it mostly sorted out.  Running a few tests, and then will probably merge it.
